<?xml version="1.0" encoding="utf-8"?><Database Name="PS_TALLER" Class="PlantillaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=PS_TALLER;Persist Security Info=True;User ID=sa" SettingsObjectName="Plantilla.core.Properties.Settings" SettingsPropertyName="LOCAL" Provider="System.Data.SqlClient" />
  <Table Name="ATCL.ESTADOS_DEMO" Member="ESTADOS_DEMOs">
    <Type Name="ESTADOS_DEMO">
      <Column Name="ID" Type="System.String" DbType="VarChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DESCRIP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>